server:
  port: 8099
  http2:
    enabled: true
  undertow:
    decode-url: true
    threads:
      io: 8 #4core
      worker: 40 #max-threads
    url-charset: UTF-8
    always-set-keep-alive: true
    direct-buffers: true

spring:
#  redis:
  profiles:
    active: local


engine:
  idx-dir: "/home/volka/search_engine/idx"

springdoc:
  swagger-ui:
    groups-order: desc
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    default-models-expand-depth: 3
    default-model-expand-depth: 3
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  writer-with-default-pretty-printer: true
  paths-to-match:
    - /search/api/v1/**