server:
  port: 8090
  servlet:
    encoding:
      charset: UTF-8
      force-request: true
      force-response: true
    context-path: "/api/v1"

engine:
  file:
    index-path: "/path" #서버에 올릴 디렉토리 위치 정해지면 수정


